/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type Playlist = {
  _id: string;
  _type: "playlist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  select?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "startup";
  }>;
};

export type Startup = {
  _id: string;
  _type: "startup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  views?: number;
  description?: string;
  category?: string;
  image?: string;
  pitch?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  name?: string;
  username?: string;
  email?: string;
  image?: string;
  bio?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Markdown = string;

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | SanityAssetSourceData | Playlist | Startup | Author | Slug | Markdown;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: STARTUP_QUERY
// Query: *[_type=="startup" && defined(slug.current) && !defined($search)|| title match $search || category match $search || author->name match $search ]| order(_created_at){  description,    title,    _createdAt,    author -> {      _id, name, image,bio    },    category,_id,    slug,    views,    image}
export type STARTUP_QUERYResult = Array<{
  description: null;
  title: string | null;
  _createdAt: string;
  author: null;
  category: null;
  _id: string;
  slug: Slug | null;
  views: null;
  image: null;
} | {
  description: null;
  title: null;
  _createdAt: string;
  author: null;
  category: null;
  _id: string;
  slug: null;
  views: null;
  image: string | null;
} | {
  description: string | null;
  title: string | null;
  _createdAt: string;
  author: null;
  category: null;
  _id: string;
  slug: null;
  views: null;
  image: null;
} | {
  description: string | null;
  title: string | null;
  _createdAt: string;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    bio: string | null;
  } | null;
  category: string | null;
  _id: string;
  slug: Slug | null;
  views: number | null;
  image: string | null;
}>;
// Variable: STARTUPS_BY_AUTHOT_QUERY
// Query: *[_type=="startup" && author._ref ==$id]| order(_created_at){  description,    title,    _createdAt,    author -> {      _id, name, image,bio    },    category,_id,    slug,    views,    image}
export type STARTUPS_BY_AUTHOT_QUERYResult = Array<{
  description: string | null;
  title: string | null;
  _createdAt: string;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    bio: string | null;
  } | null;
  category: string | null;
  _id: string;
  slug: Slug | null;
  views: number | null;
  image: string | null;
}>;
// Variable: STARTUP_BY_ID_QUERY
// Query: *[_type=="startup" && defined(slug.current) && _id==$id][0] {  description,    title,    _createdAt,    author -> {      _id, name,username, image,bio    },    category,_id,    slug,    views,    image,    pitch}
export type STARTUP_BY_ID_QUERYResult = {
  description: string | null;
  title: string | null;
  _createdAt: string;
  author: {
    _id: string;
    name: string | null;
    username: string | null;
    image: string | null;
    bio: string | null;
  } | null;
  category: string | null;
  _id: string;
  slug: Slug | null;
  views: number | null;
  image: string | null;
  pitch: string | null;
} | null;
// Variable: STARTUP_COUNT_QUERY
// Query: *[_type=="startup" && defined(slug.current) && _id==$id][0] {  views, _id}
export type STARTUP_COUNT_QUERYResult = {
  views: number | null;
  _id: string;
} | null;
// Variable: AUTHOR_BY_GITHUB_ID_QUERY
// Query: *[_type=="author" && id==$id][0] {    id, _id, bio, image, name, username, email,  }
export type AUTHOR_BY_GITHUB_ID_QUERYResult = {
  id: number | null;
  _id: string;
  bio: string | null;
  image: string | null;
  name: string | null;
  username: string | null;
  email: string | null;
} | null;
// Variable: AUTHOR_BY_ID_QUERY
// Query: *[_type=="author" && _id==$id][0] {    id, _id, bio, image, name, username, email,  }
export type AUTHOR_BY_ID_QUERYResult = {
  id: number | null;
  _id: string;
  bio: string | null;
  image: string | null;
  name: string | null;
  username: string | null;
  email: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type==\"startup\" && defined(slug.current) && !defined($search)|| title match $search || category match $search || author->name match $search ]| order(_created_at){\n  description,\n    title,\n    _createdAt,\n    author -> {\n      _id, name, image,bio\n    },\n    category,_id,\n    slug,\n    views,\n    image\n}": STARTUP_QUERYResult;
    "*[_type==\"startup\" && author._ref ==$id]| order(_created_at){\n  description,\n    title,\n    _createdAt,\n    author -> {\n      _id, name, image,bio\n    },\n    category,_id,\n    slug,\n    views,\n    image\n}": STARTUPS_BY_AUTHOT_QUERYResult;
    "*[_type==\"startup\" && defined(slug.current) && _id==$id][0] {\n  description,\n    title,\n    _createdAt,\n    author -> {\n      _id, name,username, image,bio\n    },\n    category,_id,\n    slug,\n    views,\n    image,\n    pitch\n}": STARTUP_BY_ID_QUERYResult;
    "*[_type==\"startup\" && defined(slug.current) && _id==$id][0] {\n  views, _id\n}": STARTUP_COUNT_QUERYResult;
    "*[_type==\"author\" && id==$id][0] {\n    id, _id, bio, image, name, username, email,\n  }": AUTHOR_BY_GITHUB_ID_QUERYResult;
    "*[_type==\"author\" && _id==$id][0] {\n    id, _id, bio, image, name, username, email,\n  }": AUTHOR_BY_ID_QUERYResult;
  }
}
